### ISSUE TITLE
Error in `README` snippet. `RecipeTransform` vs `TransformResult`

### ISSUE THREAD

**Issue by zilto** [ibis-project/ibisml#24] opened 2024-03-03 16:58 UTC
The README includes the following snippet which has errors (I added type hints for readability)

```python
import ibis
import ibisml

train = ibis.read_csv(...)

recipe: ibisml.Recipe = ibisml.Recipe()
transform: ibisml.RecipeTransform = recipe.fit(train, outcomes=["outcome_col"])

df_train: pd.DataFrame = transform(train).to_pandas()
X = df_train[transform.features]  # <- ibisml.RecipeTransform doesn't have `.features` or `.outcomes attributes
y = df_train[transform.outcomes]
```

Code needs to be refactored to 
```python
recipe: ibisml.Recipe = ibisml.Recipe()
transform: ibisml.RecipeTransform = recipe.fit(train, outcomes=["outcome_col"])

train_fitted: ibisml.TransformResult = transform(train)  # <- ibisml.TransformResult has `.features` or `.outcomes attributes
df_train: pd.DataFrame = train_fitted.to_pandas()
X = df_train[train_fitted.features]  # <- ibisml.TransformResult has `.features` or `.outcomes attributes
y = df_train[train_fitted.outcomes]
```

I don't know the motivations behind separating `Recipe`, `RecipeTransform`, and `TransformResult`. What raises questions is that both the `transform` and the `train_fitted` objects need to access `train`, but only the latter has `.features` and `.outcomes` set. Users coming from scikit-learn would expect 2 "layers" instead of 3 with `Recipe` (with a `fitted: bool` flag) and some sort of result. 

Maybe a relevant distinction for users is that you should store `RecipeTransform` or `TransformResult` when you need matching training/inference pipelines, and store `Recipe` want you intend to reuse a pipeline across datasets/feature sets/model versions.

I'm familiar with the [scikit-learn code conventions](https://scikit-learn.org/stable/developers/develop.html#instantiation) (which are not perfect), but the following sections on instantiation, fitting, and estimated attributes might be relevant. Transformer/Estimator parameters are only set by `__init__` and `set_params` (essentially the ibisml.Recipe part of the API) and attributes derived from the data all have a trailing underscore. For instance, we would have `.features_` derived from `train` and `.outcomes_` is received during `.fit()` instead of `__init__`

**Comment by deepyaman** [comment] 2024-03-04 23:37
@zilto Thanks for flagging! Good catch.

> I don't know the motivations behind separating `Recipe`, `RecipeTransform`, and `TransformResult`. What raises questions is that both the `transform` and the `train_fitted` objects need to access `train`, but only the latter has `.features` and `.outcomes` set. Users coming from scikit-learn would expect 2 "layers" instead of 3 with `Recipe` (with a `fitted: bool` flag) and some sort of result.

I don't want to speak for him, but @jcrist is wrapping up a refactor that will reduce the "layers" in Ibis-ML. Hopefully some of this will resonate.

I can say that Ibis-ML was designed with intentional differences from scikit-learn (it's more tidymodels-inpired), but, again, @jcrist can definitely elaborate better on some of these points at this time, as the original author.

**Comment by zilto** [comment] 2024-03-08 22:32
Thanks for the context! I essentially opened issue to share the bug in the code snippet, so feel free to close the issue

**Comment by deepyaman** [comment] 2024-03-19 22:36
@zilto Closing this because the API, including the code snippet, has changed. We will also try to add some end-to-end examples soon!

**Comment by deepyaman** [comment] 2024-03-19 22:36
@zilto Closing this because the API, including the code snippet, has changed. We will also try to add some end-to-end examples soon!

**Closed by deepyaman** 2024-03-19 22:36 UTC
